version: "3.8"

services:
  nginx1:
    image: nginx
    container_name: nginx1
    volumes:
      - type: volume
        source: mein-volume
        target: /data

      - ./bind-folder:/app

      - type: tmpfs
        target: /temp

  nginx2:
    image: nginx
    container_name: nginx2
    volumes:
      - mein-volume:/data

volumes:
  mein-volume: